## Evaluate Alex's coscientist QA on gemini 2.5 pro using arize pheonix qa evaluators

In [1]:
# %pip install pdfplumber

In [2]:
# %pip install -qq "arize-phoenix-evals" ipython matplotlib pycm scikit-learn tiktoken nest_asyncio 'httpx<0.28'
# %pip install langchain_google_vertexai google-cloud-aiplatform

In [4]:
from google.cloud.aiplatform import init as init_vertexai
PROJECT_ID = "seequent-labs-dev"
LOCATION = "us-central1"
init_vertexai(project=PROJECT_ID, location=LOCATION)

# Run Gemini 2.5-pro QA agent, evaluate with custom structured output,
# log everything as a Phoenix experiment.

In [ ]:


# --------------------------------------------------------------------
import os, re, pdfplumber, pandas as pd
from pathlib import Path
from datetime import datetime
from typing import Dict, Any

import phoenix as px
from phoenix.otel import register
from openinference.instrumentation.langchain import LangChainInstrumentor
from openinference.instrumentation import using_attributes
from phoenix.experiments import run_experiment
from phoenix.experiments.evaluators.utils import create_evaluator

from langchain_google_vertexai import ChatVertexAI
from langchain.schema import SystemMessage, HumanMessage
from langchain_core.pydantic_v1 import BaseModel, Field
from opentelemetry import trace                           # for manual spans

# ------------------------  CONFIG  -------------------------------
PROJECT_ID, LOCATION = "seequent-labs-dev", "us-central1"
PROJECT_NAME         = "alex-qa-coscientist-gemini"
PARENT_PATH          = Path().cwd().parent.parent
PDF_FILE             = PARENT_PATH / "data" / "qa" / "Q and A for AI evaluation.pdf"

os.environ["PHOENIX_COLLECTOR_ENDPOINT"] = "http://localhost:6006"
os.environ["PHOENIX_PROJECT_NAME"]       = PROJECT_NAME
# px.launch_app() or follow https://arize.com/docs/phoenix/self-hosting/deployment-options/docker

# -----------------------------------------------------------------

# Phoenix tracer
tracer_provider = register(project_name=PROJECT_NAME, auto_instrument=True)
LangChainInstrumentor().instrument(tracer_provider=tracer_provider)
tracer = tracer_provider.get_tracer(__name__)

# LLMs
agent_llm = ChatVertexAI(model_name="gemini-2.5-pro",  temperature=0.0) #llm running the agent
eval_llm  = ChatVertexAI(model_name="gemini-2.5-flash", temperature=0.0) #llm running the eval

# ------------------  DATA  ---------------------------------------
import re
from pathlib import Path
import pandas as pd
import pdfplumber

def pdf_to_df(pdf_path: Path) -> pd.DataFrame:
    """
    Extract question-answer pairs from a PDF that uses the markers
    '--Question:' and '--Answer:'.  
    Questions without a corresponding answer are skipped.
    """
    # Read the full PDF into a single text string
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text() or ""
            text += page_text + "\n"

    # Normalize whitespace
    text = re.sub(r"\r\n|\r", "\n", text)
    text = re.sub(r"\n+", " ", text)  # Convert all line breaks to spaces
    text = re.sub(r"\s+", " ", text)  # Collapse multiple spaces
    text = text.strip()

    # Split the text into sections starting with --Question:
    question_sections = re.split(r"--Question:\s*", text)[1:]  # Skip empty first element
    
    pairs = []
    
    for section in question_sections:
        section = section.strip()
        
        # Check if this section contains an answer
        if "--Answer" in section:
            # Split at the first occurrence of --Answer (with or without colon)
            answer_match = re.search(r"--Answer\s*:?\s*", section)
            if answer_match:
                question_part = section[:answer_match.start()].strip()
                answer_part = section[answer_match.end():].strip()
                
                # Clean up the question part - remove any trailing answer content
                question_part = re.sub(r"\s*--Answer.*$", "", question_part).strip()
                
                # Clean up the answer part - remove any next question
                answer_part = re.sub(r"\s*--Question:.*$", "", answer_part).strip()
                
                # Only add if both question and answer exist and are non-empty
                if question_part and answer_part:
                    pairs.append((question_part, answer_part))
        # Skip sections without answers (as requested)
    
    return pd.DataFrame(pairs, columns=["input", "expected"])




# -----------------------------------------------------------------

# ------------------  AGENT TASK  ---------------------------------
def agent_task(output: str=None, expected:str=None, input:str="", metadata:dict|None=None) -> str:  # noqa
    """Phoenix task signature is unconstrained, but we ignore params & use internal data."""
    question=input['input']

    print(f"input: {question}\n")
    # print(f"expected: {expected}\n")
    # print(f"output: {output}\n")

    system   = "You are a helpful geostatistical assistant. Answer clearly (≤300 words), plain text. Mention any potential problems or solutions as needed."

    msgs     = [SystemMessage(content=system), HumanMessage(content=question)]

    with tracer.start_as_current_span("qa_task", kind=trace.SpanKind.CLIENT) as span:
        span.set_attribute("input", question)
        answer = agent_llm.invoke(msgs).content
        span.set_attribute("output", answer)
        return answer
# -----------------------------------------------------------------

# ------------------  CUSTOM Pydantic SCHEMA  ---------------------

# Define Pydantic Schema for Evaluation Response
class EvalResp(BaseModel):
    """Schema for evaluation response with correct/incorrect classification and explanation."""
    
    correctness: str = Field(
        description="Either 'CORRECT' if the AI answer matches the reference answer, or 'INCORRECT' if it doesn't match or is wrong"
    )
    explanation: str = Field(
        description="Brief explanation of why the AI answer is correct or incorrect compared to the reference answer"
    )


# ------------------  EVALUATOR  ----------------------------------

def map_correctness(correctness_str: str) -> int:
    """Map correctness string to binary value.
    This is a pre-requsite for the evaluator to work (i.e. the evaluator returns have to be int or float)"""
    mapper = {'CORRECT': 1, 'INCORRECT': 0}
    return mapper.get(correctness_str.upper(), 0)  # Default to 0 if not found

@create_evaluator(name="structured_correctness")
def structured_eval(output: str, expected: str, input: str = "", metadata: dict|None = None) -> Dict[str, Any]:
    """Phoenix-compliant evaluator: returns dict with keys => dataframe cols."""

    question=input['input'] # inputs are a dict, so we access the 'input' key
    expected=expected['expected'] # expected is a dict with 'expected' key, so we access it
    print(f"input: {question}\n")
    print(f"expected: {expected}\n")
    print(f"output: {output}\n")

    prompt = (
        f"You are an expert evaluator.\n\n"
        f"Question: {question}\n\n"
        f"Reference Answer: {expected}\n\n"
        f"AI Answer: {output}\n\n"
        """Compare the AI answer to the human ground truth answer, if the AI correctly answers the question,
        then the AI answer is "CORRECT". If the AI answer is longer but contains the main concepts of the
        Human answer please answer "CORRECT". If the AI answer diverges or does not contain the main
        concepts of the human answer, please answer "INCORRECT". If some concepts are missing, answer "INCORRECT".
        Terminology can be different slightly for the answer to be correct; if it is different to a degree that
        it alters the meaning, please answer "INCORRECT". If the AI answer is not relevant to the question, please answer "INCORRECT".
        Respond JSON with keys correctness ('CORRECT'/'INCORRECT') and explanation of your answer (brief)."""

    )
    structured_client = eval_llm.with_structured_output(EvalResp)
    resp: EvalResp = structured_client.invoke([HumanMessage(content=prompt)])


    return (                                # expected eval return is either an int/float value or a tuple of (float/int, string), where string is an explanation of the score
        map_correctness(resp.correctness),  
        resp.explanation,
    )



def safe_upload_dataset(dataframe, dataset_name, input_keys, output_keys):
    """
    Check if dataset exists first, then upload only if needed.
    """
    phoenix_client = px.Client()
    
    # Check existing datasets
    try:
        existing_dataset = phoenix_client.get_dataset(name=dataset_name)
        if existing_dataset:
            print(f"📋 Dataset '{dataset_name}' already exists - using existing version v{existing_dataset.version_id[:8]}")
            return existing_dataset
    except ValueError as e:
        # Dataset doesn't exist - proceed to upload
        print(f"📋 Dataset '{dataset_name}' does not exist - creating new dataset.")
        try:
            with using_attributes(
                metadata={
                    "description": "Upload new dataset to Phoenix",
                }
            ):
                exp_dataset = phoenix_client.upload_dataset(
                    dataframe=dataframe,
                    dataset_name=dataset_name,
                    input_keys=input_keys,
                    output_keys=output_keys,
                )
                print(f"📦 Uploaded new dataset v{exp_dataset.version_id[:8]} with {len(dataframe)} rows.")
                return exp_dataset
        except:
                print(f"📋 Error. Dataset '{dataset_name}' was created by another process")

    except Exception as e:
        print(f"❌ Unexpected error checking dataset: {e}")
        return None

# Usage
# Clean up the PDF file, convert into pandas df
raw_df = pdf_to_df(PDF_FILE)

# Ensure the DataFrame has the correct columns
exp_dataset = safe_upload_dataset(
    dataframe=raw_df,
    dataset_name=f"{PROJECT_NAME}_ds",
    input_keys=["input"],
    output_keys=["expected"]
)

# ------------------  RUN EXPERIMENT  -----------------------------
exp_name = f"{PROJECT_NAME}_exp_{datetime.utcnow():%Y%m%d_%H%M%S}"

exp_results = run_experiment(
    dataset           = exp_dataset,
    task              = agent_task,
    evaluators        = [structured_eval],
    experiment_name   = exp_name,
    experiment_description="Gemini 2.5-pro QA agent with custom correctness evaluator",
    concurrency       = 5,
)
print(f"✅ Experiment '{exp_name}' finished. View in Phoenix UI.")

Overriding of current TracerProvider is not allowed
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented

🔭 OpenTelemetry Tracing Details 🔭
|  Phoenix Project: alex-qa-coscientist-gemini
|  Span Processor: SimpleSpanProcessor
|  Collector Endpoint: localhost:4317
|  Transport: gRPC
|  Transport Headers: {'user-agent': '****'}
|
|  Using a default SpanProcessor. `add_span_processor` will overwrite this default.
|
|  ⚠️ WARNING: It is strongly advised to use a BatchSpanProcessor in production environments.
|
|  `register` has set this TracerProvider as the global OpenTelemetry default.
|  To disable this behavior, call `register` with `set_global_tracer_provider=False`.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
/var/folders/z8/r7gby1gs0ts1089jpzfjwfjc0000gp/T/ipykernel_17330/1534695273.py:223: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  exp_name = f"{PROJECT_NAME}_exp_{datetime.utcnow():%Y%m%d_%H%M%S}"
🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

📋 Dataset 'alex-qa-coscientist-gemini_ds' already exists - using existing version vRGF0YXNl
🧪 Experiment started.
📺 View dataset experiments: http://localhost:6006/datasets/RGF0YXNldDox/experiments
🔗 View this experiment: http://localhost:6006/datasets/RGF0YXNldDox/compare?experimentId=RXhwZXJpbWVudDo1

running tasks |          | 0/13 (0.0%) | ⏳ 00:00<? | ?it/s

input: How can I compute statistics from drillhole assays?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |▊         | 1/13 (7.7%) | ⏳ 00:23<04:39 | 23.32s/it

input: What is the challenge with resource estimation of gold deposit

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |█▌        | 2/13 (15.4%) | ⏳ 00:41<03:42 | 20.20s/it

input: Why is domaining for resource estimation?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |██▎       | 3/13 (23.1%) | ⏳ 00:58<03:06 | 18.61s/it

input: What is a swath plot and how to interpret it?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |███       | 4/13 (30.8%) | ⏳ 01:14<02:40 | 17.85s/it

input: What is the difference between an estimation and a geostatistical simulation?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |███▊      | 5/13 (38.5%) | ⏳ 01:29<02:13 | 16.68s/it

input: Why do we need a variogram model to do a geostatistical estimation and simulation?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |████▌     | 6/13 (46.2%) | ⏳ 01:45<01:56 | 16.62s/it

input: Does inverse distance weighting needs a variogram mode?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |█████▍    | 7/13 (53.8%) | ⏳ 02:01<01:38 | 16.34s/it

input: Describe a typical geostatistical simulation workflow?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |██████▏   | 8/13 (61.5%) | ⏳ 02:21<01:28 | 17.62s/it

input: How many geostatistical simulations should I do?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |██████▉   | 9/13 (69.2%) | ⏳ 02:41<01:12 | 18.16s/it

input: How can I characterize the geological uncertainty?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |███████▋  | 10/13 (76.9%) | ⏳ 03:00<00:55 | 18.60s/it

input: What is a normal score transform of the data and when is it necessary?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |████████▍ | 11/13 (84.6%) | ⏳ 03:16<00:35 | 17.59s/it

input: Is Seequent using GSLIB to do geostatistics.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |█████████▏| 12/13 (92.3%) | ⏳ 03:32<00:17 | 17.27s/it

input: What is change of support and why is it important?

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running tasks |██████████| 13/13 (100.0%) | ⏳ 03:51<00:00 | 17.83s/it
🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

✅ Task runs completed.
🧠 Evaluation started.

running experiment evaluations |          | 0/13 (0.0%) | ⏳ 00:00<? | ?it/s

input: How can I compute statistics from drillhole assays?

expected: There are two challenges when doing statistical analysis of drillholes assays. 1- The samples are not the same length; so it has different support in geostatistics terms. We have two options; the first one is to weight each sample by its length. The second one is to composite the assays into regular interval. 2- The drillholes are spatially clustered, that it preferentially located in typically zones of high interests. This creates a statistical bias that often overestimate the mean and the variance of the data. The solution is to first decluster the data with a geostatistical approach. Note that delustering is typically done on compositing data.

output: Computing statistics from drillhole assays involves a standard workflow to ensure the results are meaningful for resource estimation.

**1. Data Preparation and Compositing:**
First, validate your data for errors (e.g., overlapping intervals, typos). Then, composite your raw assay data. Compositing creates equal-length samples (e.g., 1m or 5ft) down the hole. This is crucial because it removes statistical bias caused by variable sample lengths, ensuring that no single sample has undue influence on the average grade.

**2. Domain Analysis:**
Group your composited data into geological domains. These are distinct zones based on rock type, alteration, or mineralization style. It is essential to analyze statistics for each domain separately, as combining them can produce misleading results.

**3. Basic Statistical Calculation:**
For each domain, calculate fundamental statistics:
*   **Count:** Number of samples.
*   **Mean:** The average grade.
*   **Median:** The middle value, less affected by outliers.
*   **Standard Deviation:** Measures data spread.
*   **Coefficient of Variation (CV):** The standard deviation divided by the mean. A high CV (typically >1.2) indicates high variability and skewed data.

**4. Outlier Analysis (Top-Cutting):**
Visualize the data using a histogram or probability plot. Assay data is often skewed by a few extremely high-grade values (outliers). These can inflate the mean grade unrealistically. To manage this, apply a "top-cut" or "cap," where you reduce these high values to a specific threshold before recalculating statistics.

These tasks are performed using spreadsheet software, specialized mining packages (like Leapfrog, Vulcan, or Datamine), or programming languages like Python.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |▊         | 1/13 (7.7%) | ⏳ 00:08<01:38 |  8.21s/it

input: What is the challenge with resource estimation of gold deposit

expected: Gold is particularly difficult since the value of a deposit is often controlled by the a few percentages of the samples that shows very high gold grade content. This create very positively skewed distribution (lots of low value and few high values) and variograms that are difficult to model. Changing the a few high-grade samples such as with capping for instance can have a significant impact on the resource.

output: The primary challenge with resource estimation of a gold deposit is the "nugget effect."

Unlike base metals that are often distributed more evenly, gold is frequently concentrated in small, high-grade pockets, veins, or coarse nuggets. This extreme variability makes it very difficult to get a representative sample.

A drill hole might intersect a rich vein and return a very high-grade assay, leading to an overestimation of the resource. Conversely, a drill hole just a few feet away could miss that vein entirely, suggesting the area is barren and leading to an underestimation. This makes it hard to calculate a reliable average grade for the entire deposit.

Imagine trying to figure out the average number of chocolate chips in a cookie by taking one tiny bite. You might get a mouthful of chips or none at all, neither of which represents the whole cookie.

Other key challenges include:

*   **Geological Complexity:** Gold deposits are often found in complex geological structures with faults and folds. If the geological model is wrong, the resource estimate will be inaccurate.

*   **Sampling Cost:** To overcome the nugget effect, a high density of expensive drilling is required to build confidence in the estimate. This creates a trade-off between cost and certainty.

*   **Data Quality:** The entire estimate depends on the accuracy of sample collection and laboratory analysis. Any errors can lead to a flawed model.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |█▌        | 2/13 (15.4%) | ⏳ 00:13<01:12 |  6.62s/it

input: Why is domaining for resource estimation?

expected: Domaining is the process of partitioning a deposit into several parts that are statistically amenable for geostatistics. Resource estimation is not the only reason to do domaining, it can also be done for geological and geometallurgical studies. An often-used approach is to do the spatial portioning using the geology of the deposit, that is segmenting the deposit space by geology. Leapfrog is often used in that context. The assumption here, is that the grade within a geological domain is well-behaved and can be used for geostatistical studies.

output: Domaining is the process of dividing a mineral deposit into distinct zones, or "domains," based on geological characteristics. It is a critical first step in resource estimation because geology is rarely uniform.

Think of it like separating different types of fruit in a large basket before counting them. If you have high-grade gold veins, lower-grade surrounding rock, and barren waste rock all mixed together, you need to define the boundaries of each.

The main reasons for domaining are:

1.  **Geological Control:** It ensures that estimates are based on geologically similar materials. Different rock types or mineralisation styles have different grades, densities, and shapes. Grouping them separately respects these natural boundaries.

2.  **Statistical Accuracy:** Each domain represents a single statistical population. Trying to calculate an average grade by mixing high-grade and low-grade samples would produce a misleading result. It would smear the high grades into low-grade areas and dilute the true value of the high-grade zones.

3.  **Improved Confidence:** By estimating each domain separately and then combining the results, you create a more accurate and reliable resource model. This robust model is essential for making sound financial and operational decisions about whether a project is economically viable to mine.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |██▎       | 3/13 (23.1%) | ⏳ 00:21<01:10 |  7.07s/it

input: What is a swath plot and how to interpret it?

expected: A swath plot is a graphical tool used in geostatistical studies to validate block models. It helps in comparing the estimated values from the block model against the actual sample data along a specific direction or swath. This comparison is crucial for ensuring that the block model accurately represents the spatial distribution of the variable of interest. Role of a Swath Plot in Block Model Validation -Visual Comparison: Swath plots provide a visual comparison between the estimated values from the block model and the actual sample data. This helps in identifying any discrepancies or biases in the model. -Spatial Trends: They help in understanding the spatial trends and continuity of the variable being modeled. Any significant deviations between the model and the sample data can indicate issues with the model. -Model Accuracy: By comparing the block model estimates with the actual data, swath plots help in assessing the accuracy and reliability of the block model. Steps to Interpret a Swath Plot -Generate the Swath Plot: Create a swath plot by plotting the estimated values from the block model and the actual sample data along a specific direction (e.g., north-south, east- west, or vertical). -Compare Trends: Look for overall trends in both the block model estimates and the sample data. The trends should generally match if the block model is accurate. -Identify Deviations: Identify any significant deviations between the block model estimates and the sample data. Large deviations may indicate issues with the model, such as overestimation or underestimation. -Check for Bias: Assess whether there is any systematic bias in the block model. For example, if the block model consistently overestimates or underestimates the values compared to the sample data, this indicates a bias. -Evaluate Spatial Continuity: Ensure that the spatial continuity of the variable is well- represented in the block model. The swath plot should show smooth transitions without abrupt changes unless justified by the geology. -Adjust the Model: If significant issues are identified, adjust the block model parameters or the estimation method to improve the model's accuracy and reduce discrepancies. By following these steps, you can effectively use swath plots to validate and improve the quality of your block model in geostatistical studies.

output: A swath plot is a graph used in geostatistics to visually check the accuracy of a spatial estimation model (like one made with kriging). It helps validate if the model's predictions are a good match for the original sample data.

The plot is created by dividing a study area into parallel slices, or "swaths," along a specific direction (e.g., east-west). For each swath, the tool calculates two values: the average of the original sample data points and the average of the model's estimated values.

How to Interpret It:

A swath plot typically shows two lines on a graph. The x-axis represents the location of the swaths, and the y-axis represents the value of the variable being studied (e.g., mineral grade, pollutant level).

1.  The Sample Data Line: This line connects the average values of the raw data in each swath. It is usually more jagged, showing the natural variability.

2.  The Estimated Model Line: This line connects the average values from your estimation model. It is typically smoother.

Your goal is to see how well these two lines match.

-   If the lines are close together and follow the same general trend, your model is performing well.
-   If the estimate line is consistently above or below the data line, your model has a bias (it is systematically over- or under-predicting).
-   The estimate line will almost always be smoother than the data line. This is expected and is known as the "smoothing effect" of estimation.

By creating plots for different directions (e.g., north-south and east-west), you can check if your model is accurate across the entire area.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |███       | 4/13 (30.8%) | ⏳ 00:29<01:08 |  7.66s/it

input: What is the difference between an estimation and a geostatistical simulation?

expected: Two common geostatistical methods are kriging and conditional simulation. Kriging provides the best linear unbiased local prediction by minimizing the estimation variance, while conditional simulation generates multiple equally probable realizations to assess uncertainty. Kriging should be selected when having local precision is important, but we do not need to characterize the uncertainty, or we do not need to represent the true spatial heterogeneity (patterns or texture) of the phenomenon. In contrast, one should choose simulation whenever the spatial context is important and that uncertainty is important for decision making. Note that can get local accuracy with a very large set of simulations.

output: An estimation provides a single, best guess of values, while a geostatistical simulation generates multiple, equally probable versions of reality.

Estimation, such as kriging, aims to find the most likely value at each unsampled location. The result is a single map that is typically smooth because it averages information from nearby data points. Its primary goal is to minimize local error, providing the best prediction on a point-by-point basis.

In contrast, geostatistical simulation does not try to create the "best" map. Instead, it produces many possible maps, called realizations. Each realization honors the original data points and reproduces the overall statistical properties of the dataset, such as its mean, variance, and spatial structure. These maps look more realistic and capture the full range of spatial variability, including extreme high and low values.

In short, use estimation when you need the single most probable answer. Use simulation when you need to understand the range of possibilities and assess uncertainty or risk.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |███▊      | 5/13 (38.5%) | ⏳ 00:35<00:55 |  6.90s/it

input: Why do we need a variogram model to do a geostatistical estimation and simulation?

expected: Kriging and simulations require variograms that describe the spatial correlation structure of the data. The variogram is a fundamental tool in geostatistics that quantifies how data similarity decreases with distance. It is used to model the spatial continuity and anisotropy and to inform the weighting of sampled data points in the estimation process. By fitting a variogram model to the empirical variogram, geostatisticians can make more accurate predictions and better understand the spatial variability of the studied phenomenon.

output: A variogram model is a mathematical function that describes the spatial correlation in your data. We need this model to perform geostatistical estimation (like Kriging) and simulation for three main reasons:

1.  **Provides Continuous Information:** The variogram you calculate directly from your data (the empirical variogram) only provides values at specific distances (lags). Kriging needs to know the spatial relationship for the *exact* distances between your sample points and the location you want to estimate. A continuous model can provide a valid semivariance value for any distance, not just the ones you calculated.

2.  **Ensures Mathematical Validity:** Kriging equations require the variance-covariance matrix to be "positive definite" to ensure a unique and stable solution. A raw, bumpy empirical variogram does not guarantee this property and can lead to nonsensical results, like negative variances. Authorized variogram models (e.g., spherical, exponential, Gaussian) are specifically designed to be mathematically valid, ensuring the calculations work correctly.

3.  **Smooths and Generalizes:** The empirical variogram is often noisy due to sampling irregularities. The model smooths out this noise to represent the underlying spatial structure of the phenomenon itself, rather than the quirks of your specific dataset. This provides a more robust basis for estimation and for creating realistic simulations.

In short, the empirical variogram is a set of raw data points describing spatial correlation. The variogram model is the "line of best fit" that turns those points into a continuous, mathematically sound rule that geostatistical algorithms can use.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |████▌     | 6/13 (46.2%) | ⏳ 00:41<00:46 |  6.71s/it

input: Does inverse distance weighting needs a variogram mode?

expected: No. Inverse distance weighting (IDW) is a simpler estimation technique that does not use a variogram and is not typically as accurate as Kriging.

output: No, Inverse Distance Weighting (IDW) does not need a variogram model.

IDW is a simple, deterministic interpolation method. It calculates a value for an unknown location by taking a weighted average of known surrounding data points. The weights are based solely on the distance between the unknown point and the known points. Closer points are given a higher weight than points farther away, following the principle that "things that are closer are more related." The user only needs to define a power parameter that controls how rapidly the influence of a point decreases with distance.

The variogram model is a key component of a different, more complex group of interpolation methods called **Kriging**.

In Kriging, the variogram is used to describe the spatial autocorrelation of the data—how the similarity between data points changes with distance. Kriging uses this model to determine the optimal weights for interpolation, providing a more statistically robust estimate and a measure of prediction error.

In summary:
*   **IDW** uses only distance to determine weights.
*   **Kriging** uses a variogram model (which is derived from the data's spatial structure) to determine weights.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |█████▍    | 7/13 (53.8%) | ⏳ 00:47<00:37 |  6.28s/it

input: Describe a typical geostatistical simulation workflow?

expected: Geostatistical workflows typically start with data exploration. domaining and declustering to removes biases in the data sampling to get an accurate mean and variance of the samples. Removing sampling biases are important to estimate the mean grade and the tonnage of the deposit. The typical estimation continues with variogram modelling. The samples and the data will then be used to parameterize the Kriging function to interpolate the sample on a block model. The validation of an estimation model consists of checking the swath plots and to compare the statistics between the estimated values and the sample values.

output: A typical geostatistical simulation workflow generates multiple, equally probable maps (realizations) of a spatial property to quantify uncertainty.

The process begins with Exploratory Data Analysis (EDA). This involves examining the input data's statistical distribution with tools like histograms and understanding its spatial continuity. Spatial continuity is quantified by calculating an experimental variogram and fitting a mathematical model to it. This variogram model captures how data values are related over distance.

Next, the data is often transformed to a standard normal distribution (a normal score transform), as this is a requirement for many common simulation algorithms.

The core step is the simulation itself, frequently performed using an algorithm like Sequential Gaussian Simulation (SGS). SGS defines a grid over the area of interest. It then simulates values at each grid node one by one, ensuring that each new value honors the original data, the target histogram, and the variogram model. This entire process is repeated many times (e.g., 100 times) with different random seeds to create a set of realizations.

Finally, the simulated values are back-transformed to their original units. This collection of maps is used for post-processing. From these realizations, you can calculate an average map, a variance map to visualize uncertainty, or perform risk analysis, such as finding the probability that a value will exceed a critical threshold.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |██████▏   | 8/13 (61.5%) | ⏳ 00:54<00:32 |  6.49s/it

input: How many geostatistical simulations should I do?

expected: The number of simulations depends on the objective of the study, the density of the data and the spatial continuity of the grades. For instance, for simple statistical validation, a few, say three to ten, is enough to analyze their quality in terms of the reproduction of the grade distribution and variogram (spatial continuity). Once, a modeler can create simulation of high quality, 100 simulations is typically a good start given the speed of performing simulation on Seequent Evo. The right number should be viewed in terms of the objectives and the decision-making inherent to the modeling exercise. Would adding more simulation to the ensemble would change the decisions? One can test that by dividing the ensemble of 100 simulations in two ensembles of fifty and make the decision for each ensemble? If each ensemble drives to different decision, then one should seriously consider adding another set of 100 simulations to the ensemble. That analysis can then be repeated with the augmented ensemble.

output: There is no single magic number for how many geostatistical simulations (or "realizations") to run. The correct number depends on your specific goal. The guiding principle is to run enough simulations until the statistics you care about become stable.

Here is a practical approach to determine the number:

1.  **Define Your Objective:** What are you trying to measure? Is it the average grade of a block model? The total volume above a cutoff? The connectivity of a high-grade zone? Or the uncertainty range (e.g., the P10 and P90 values)?

2.  **Check for Stability:** Start with a reasonable number, like 100 simulations. Calculate the key statistic you need (e.g., the average grade). Then, run another 100 simulations (for a total of 200) and recalculate that same statistic. If the value has not changed significantly, 200 is likely enough. If it is still fluctuating, you need to run more simulations until the result stabilizes.

**General Rules of Thumb:**

*   **For stable global statistics** (like the overall mean or variance of the entire model), **100 to 200 realizations** are often sufficient.

*   **For more sensitive or local statistics** (like the connectivity of extreme values, flow simulation results, or specific quantiles like P10/P90), you will likely need more. It is common to use **500 to 1,000 realizations** or more in these cases.

In short, the number is driven by the stability of your desired output, balancing the need for precision against computational time.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |██████▉   | 9/13 (69.2%) | ⏳ 01:00<00:26 |  6.59s/it

input: How can I characterize the geological uncertainty?

expected: The two main approaches are 1- Create several geological models (scenarios) with Leapfrog. Each model represents a possible interpretation of the underlying geology. 2- Simulate the geology using a geostatistical approach such as indicator simulation or plurigaussian simulations.

output: Characterizing geological uncertainty means defining the range of possible subsurface conditions based on limited data. Since we can only sample the earth at specific points (e.g., boreholes, seismic lines), we must account for the unknown variations between them.

There are two primary approaches to do this.

First, qualitative methods describe uncertainty using scenarios. This involves creating "best case," "most likely," and "worst case" geological models. For example, a fault might be interpreted as sealing (best case) or leaking (worst case). This approach helps stakeholders understand the range of possibilities without complex statistics. Risk maps can also classify areas by their level of uncertainty (low, medium, high).

Second, quantitative methods use statistics to put numbers on the uncertainty. Geostatistics is the core discipline here. A key method is stochastic modeling, which uses algorithms to generate hundreds or thousands of equally probable geological models that all honor the known data. By analyzing the full range of outcomes from these models (e.g., mineral volume, groundwater flow), you can define the uncertainty with a probability distribution. This shows the likelihood of any given outcome occurring.

The goal is not to eliminate uncertainty, which is impossible, but to quantify its potential impact. This allows for more informed, risk-based decisions in projects like resource extraction, civil engineering, or environmental management.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |███████▋  | 10/13 (76.9%) | ⏳ 01:03<00:16 |  5.45s/it

input: What is a normal score transform of the data and when is it necessary?

expected: Normal score transform or Gaussian anamorphosis is the process of transforming any distribution into a Gaussian distribution. There are several ways of achieving that; the most common is to do a quantile-to-quantile transform whereas the each sample is transformed into a Gaussian deviate with the same quantiles. The challenge in this technique is the application of the declustering weights and the duplicate of data. It is common that a sizeable percentage of data will have the same value, e.g. detection limit or zeros, these must then go through a tie-breaking process to be transformed into a Gaussian distribution. Normal score transform is important because many simulation algorithms, such as turning bands or sequential gaussian simulation, only work in the Gaussian space. The workflow is then to transform the data into the Gaussian space, perform the simulation and then transform it back the original space (e.g. gold grades).

output: A normal score transform, also known as a quantile transformation, is a statistical procedure that converts your data to follow a normal (or "bell curve") distribution.

The process works by first ranking your data points from smallest to largest. Each data point is then replaced by the value it would have if it came from a standard normal distribution based on its rank. For example, the median value of your data is replaced with 0 (the median of a standard normal distribution), and values below the median are replaced with corresponding negative scores.

This transform is necessary when you want to use a statistical method that assumes your data is normally distributed, but it isn't. Many common parametric tests, such as linear regression, ANOVA, and t-tests, rely on this assumption of normality (often for the model's errors or residuals).

If your original data is heavily skewed or has extreme outliers, these tests can produce misleading or invalid results. By applying a normal score transform, you reshape the data to meet the test's requirements, allowing you to use these powerful statistical tools more appropriately and making your analysis more reliable.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |████████▍ | 11/13 (84.6%) | ⏳ 01:10<00:11 |  5.97s/it

input: Is Seequent using GSLIB to do geostatistics.

expected: No. Seequent uses it own algorithms that has been specifically designed to run on the cloud.

output: No, Seequent does not use GSLIB as the computational engine for its geostatistical tools, such as those found in Leapfrog Geo.

Seequent has developed its own proprietary algorithms and high-performance processing engines. For example, Leapfrog's core interpolation functionality is built on its FastRBF™ engine, which is distinct from the methods used in GSLIB.

However, Seequent's software is designed to be compatible with the wider geoscience ecosystem. It acknowledges GSLIB's importance as an industry-standard format and library. Therefore, you can:

*   **Import and export data** in GSLIB's standard file formats.
*   **Compare results** between Seequent's tools and GSLIB to validate workflows.

In summary, Seequent uses its own proprietary engine for geostatistics but ensures interoperability with GSLIB, allowing users to integrate different tools into their workflows.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |█████████▏| 12/13 (92.3%) | ⏳ 01:14<00:05 |  5.30s/it

input: What is change of support and why is it important?

expected: Change of support in geostatistics refers to the process of translating spatial data or predictions from one scale to another. For instance, if you have detailed data collected at smaller spatial units (e.g., borehole samples) and you want to predict or analyze this information across larger areas or blocks (e.g., mining blocks), you need to change the support. This concept is crucial because the variability and statistical properties of the data often differ depending on the scale of measurement, and accurate modeling requires adjustments to account for these differences. Methods such as upscaling or downscaling are used to manage this transition effectively. The change of support will change the shape and characteristics of a distribution as well as the shape of the variogram. For a linear unweighted upscaling, that is averaging, the mean of the upscaled distribution will remains the same and the variance will decrease in function of the spatial continuity as measured by the variogram.

output: Change of support is the process of estimating the properties of a large area or volume based on smaller samples taken from within it. It addresses the statistical changes that occur when you move from a small measurement scale (the "support" of a sample) to a larger one (the support of a decision).

A classic example is in mining. Geologists collect small drill core samples (point support) to measure ore grade. However, the company makes decisions on whether to mine massive blocks of rock, perhaps the size of a truckload (block support). The change of support problem is how to accurately predict the average grade of that large block using the data from the small samples.

This is important for two main reasons:

1.  **Variability Decreases with Scale:** The variability of data is always lower for large volumes than for small samples. The average grade of a large block will be less extreme than the individual sample grades within it. Averages smooth out the highs and lows.

2.  **Prevents Costly Errors:** If you ignore the change of support, you might use the high-grade values from small samples to assume entire blocks are equally rich. This leads to overestimating the profitable resource, causing you to mine areas that are actually waste. This is a critical error in mining, environmental cleanup (assessing contamination), and agriculture (estimating crop yield).

In short, change of support is a crucial tool for making accurate, large-scale decisions from small-scale data, preventing significant financial and operational mistakes.

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(
running experiment evaluations |██████████| 13/13 (100.0%) | ⏳ 01:21<00:00 |  6.23s/it

🔗 View this experiment: http://localhost:6006/datasets/RGF0YXNldDox/compare?experimentId=RXhwZXJpbWVudDo1

Experiment Summary (07/18/25 11:53 AM -0600)
--------------------------------------------
                evaluator   n  n_scores  avg_score
0  structured_correctness  13        13   0.769231

Tasks Summary (07/18/25 11:51 AM -0600)
---------------------------------------
   n_examples  n_runs  n_errors
0          13      13         0
✅ Experiment 'alex-qa-coscientist-gemini_exp_20250718_174750' finished. View in Phoenix UI.

In [ ]:
exp_results.as_dataframe()

,output,input,expected,example_id
run_id,,,,
RXhwZXJpbWVudFJ1bjoyMzg=,Computing statistics from drillhole assays is ...,{'input': 'How can I compute statistics from d...,{'expected': 'There are two challenges when do...,RGF0YXNldEV4YW1wbGU6NTQ1
RXhwZXJpbWVudFJ1bjoyMzk=,The primary challenge with resource estimation...,{'input': 'What is the challenge with resource...,{'expected': 'Gold is particularly difficult s...,RGF0YXNldEV4YW1wbGU6NTQ2

In [20]:
exp_results.as_dataframe()

,output,input,expected,example_id
run_id,,,,
RXhwZXJpbWVudFJ1bjoyMzg=,Computing statistics from drillhole assays is ...,{'input': 'How can I compute statistics from d...,{'expected': 'There are two challenges when do...,RGF0YXNldEV4YW1wbGU6NTQ1
RXhwZXJpbWVudFJ1bjoyMzk=,The primary challenge with resource estimation...,{'input': 'What is the challenge with resource...,{'expected': 'Gold is particularly difficult s...,RGF0YXNldEV4YW1wbGU6NTQ2

In [14]:
eval_df

,question,correct_answer,ai_generated_answer,metadata
0,How can I compute statistics from drillhole as...,There are two challenges when doing statistica...,Computing statistics from drillhole assays is ...,{'id': 'qa_0'}
1,What is the challenge with resource estimation...,Gold is particularly difficult since the value...,The primary challenge in resource estimation f...,{'id': 'qa_1'}
2,Why is domaining for resource estimation?\n--A...,A swath plot is a graphical tool used in geost...,A swath plot is a graphical validation tool us...,{'id': 'qa_2'}
3,What is the difference between an estimation a...,Two common geostatistical methods are kriging ...,Geostatistical estimation and simulation are t...,{'id': 'qa_3'}
4,Why do we need a variogram model to do a geost...,Kriging and simulations require variograms tha...,A variogram model is essential for geostatisti...,{'id': 'qa_4'}
5,Does inverse distance weighting needs a variog...,No. Inverse distance weighting (IDW) is a simp...,"No, Inverse Distance Weighting (IDW) does not ...",{'id': 'qa_5'}
6,Describe a typical geostatistical simulation w...,Geostatistical workflows typically start with ...,A typical geostatistical simulation workflow i...,{'id': 'qa_6'}
7,Describe a typical geostatistical simulation w...,The number of simulations depends on the objec...,There is no single correct number of geostatis...,{'id': 'qa_7'}
8,How can I characterize the geological uncertai...,The two main approaches are\n1- Create several...,Characterizing geological uncertainty involves...,{'id': 'qa_8'}
9,What is a normal score transform of the data a...,Normal score transform or Gaussian anamorphosi...,A normal score transform (NST) is a data conve...,{'id': 'qa_9'}
10,Is Seequent using GSLIB to do geostatistics.,No. Seequent uses it own algorithms that has b...,"No, Seequent does not use GSLIB for its geosta...",{'id': 'qa_10'}
11,What is change of support and why is it import...,Change of support in geostatistics refers to t...,Change of support is a fundamental concept in ...,{'id': 'qa_12'}

In [27]:
eval_df

,input,reference,output,metadata
0,How can I compute statistics from drillhole as...,There are two challenges when doing statistica...,Computing statistics from drillhole assays req...,{'id': 'qa_0'}
1,What is the challenge with resource estimation...,Gold is particularly difficult since the value...,The primary challenge in estimating gold resou...,{'id': 'qa_1'}
2,Why is domaining for resource estimation?\n--A...,A swath plot is a graphical tool used in geost...,A swath plot is a graphical validation tool us...,{'id': 'qa_2'}
3,What is the difference between an estimation a...,Two common geostatistical methods are kriging ...,Geostatistical estimation and simulation are t...,{'id': 'qa_3'}
4,Why do we need a variogram model to do a geost...,Kriging and simulations require variograms tha...,A variogram model is essential for geostatisti...,{'id': 'qa_4'}
5,Does inverse distance weighting needs a variog...,No. Inverse distance weighting (IDW) is a simp...,"No, Inverse Distance Weighting (IDW) does not ...",{'id': 'qa_5'}
6,Describe a typical geostatistical simulation w...,Geostatistical workflows typically start with ...,A typical geostatistical simulation workflow i...,{'id': 'qa_6'}
7,Describe a typical geostatistical simulation w...,The number of simulations depends on the objec...,"The number of geostatistical simulations, or r...",{'id': 'qa_7'}
8,How can I characterize the geological uncertai...,The two main approaches are\n1- Create several...,Characterizing geological uncertainty involves...,{'id': 'qa_8'}
9,What is a normal score transform of the data a...,Normal score transform or Gaussian anamorphosi...,A normal score transform (NST) is a data conve...,{'id': 'qa_9'}
10,Is Seequent using GSLIB to do geostatistics.,No. Seequent uses it own algorithms that has b...,"No, Seequent software like Leapfrog Geo does n...",{'id': 'qa_10'}
11,What is change of support and why is it import...,Change of support in geostatistics refers to t...,Change of support is a fundamental concept in ...,{'id': 'qa_12'}

In [28]:
# from phoenix.trace import SpanEvaluations
# import os

# px.Client().log_evaluations(
#     SpanEvaluations(
#         dataframe=eval_results,
#         eval_name="AIvsHuman",
#     ),
# )

In [34]:
schema_results

,input,reference,output,label,explanation,metadata
0,How can I compute statistics from drillhole as...,There are two challenges when doing statistica...,Computing statistics from drillhole assays req...,CORRECT,The AI answer correctly identifies the two mai...,{'id': 'qa_0'}
1,What is the challenge with resource estimation...,Gold is particularly difficult since the value...,The primary challenge in estimating gold resou...,CORRECT,The AI answer accurately identifies the core c...,{'id': 'qa_1'}
2,Why is domaining for resource estimation?\n--A...,A swath plot is a graphical tool used in geost...,A swath plot is a graphical validation tool us...,CORRECT,"The AI answer accurately defines a swath plot,...",{'id': 'qa_2'}
3,What is the difference between an estimation a...,Two common geostatistical methods are kriging ...,Geostatistical estimation and simulation are t...,CORRECT,The AI answer accurately explains the differen...,{'id': 'qa_3'}
4,Why do we need a variogram model to do a geost...,Kriging and simulations require variograms tha...,A variogram model is essential for geostatisti...,CORRECT,The AI-generated answer is correct and provide...,{'id': 'qa_4'}
5,Does inverse distance weighting needs a variog...,No. Inverse distance weighting (IDW) is a simp...,"No, Inverse Distance Weighting (IDW) does not ...",CORRECT,The AI answer correctly states that Inverse Di...,{'id': 'qa_5'}
6,Describe a typical geostatistical simulation w...,Geostatistical workflows typically start with ...,A typical geostatistical simulation workflow i...,CORRECT,The AI-generated answer accurately describes a...,{'id': 'qa_6'}
7,Describe a typical geostatistical simulation w...,The number of simulations depends on the objec...,"The number of geostatistical simulations, or r...",CORRECT,The AI answer correctly identifies that the nu...,{'id': 'qa_7'}
8,How can I characterize the geological uncertai...,The two main approaches are\n1- Create several...,Characterizing geological uncertainty involves...,CORRECT,The AI answer correctly identifies the two mai...,{'id': 'qa_8'}
9,What is a normal score transform of the data a...,Normal score transform or Gaussian anamorphosi...,A normal score transform (NST) is a data conve...,CORRECT,The AI answer accurately defines normal score ...,{'id': 'qa_9'}
10,Is Seequent using GSLIB to do geostatistics.,No. Seequent uses it own algorithms that has b...,"No, Seequent software like Leapfrog Geo does n...",CORRECT,The AI answer correctly states that Seequent d...,{'id': 'qa_10'}
11,What is change of support and why is it import...,Change of support in geostatistics refers to t...,Change of support is a fundamental concept in ...,CORRECT,The AI-generated answer accurately defines cha...,{'id': 'qa_12'}

In [36]:
eval_results

,label,explanation,exceptions,execution_status,execution_seconds
0,None,None,"[PhoenixTemplateMappingError(""Missing template...",MISSING INPUT,0.00339
1,None,None,[],DID NOT RUN,0.00000
2,None,None,[],DID NOT RUN,0.00000
3,None,None,[],DID NOT RUN,0.00000
4,None,None,[],DID NOT RUN,0.00000
5,None,None,[],DID NOT RUN,0.00000
6,None,None,[],DID NOT RUN,0.00000
7,None,None,[],DID NOT RUN,0.00000
8,None,None,[],DID NOT RUN,0.00000
9,None,None,[],DID NOT RUN,0.00000
10,None,None,[],DID NOT RUN,0.00000
11,None,None,[],DID NOT RUN,0.00000

In [75]:
# eval_df.iloc[:1,:].to_csv(parent_path / "data" / "qa" / "alex_qa_eval_results.csv", index=False)

In [12]:
from phoenix.trace import SpanEvaluations
import os

px.Client().log_evaluations(
    SpanEvaluations(
        dataframe=eval_results,
        eval_name="AIvsHuman",
    ),
)

/Users/stepan.lavrinenko/phoenix/.venv/lib/python3.12/site-packages/phoenix/utilities/client.py:51: UserWarning: ⚠️⚠️ The Phoenix server (10.13.2) and client (11.5.0) versions are severely mismatched. Upgrade  either the client or server to ensure API compatibility ⚠️⚠️
  warnings.warn(

ValueError: The dataframe index must be ['context.span_id'] but was '[None]'